### ISSUE TITLE
 Error: Error encountered resolving symbol values statically. Calling function 'OpaqueToken', 

### ISSUE THREAD

**Issue by urstack** [cloudinary/cloudinary_angular#111]
Getting following error : 
ERROR in Error: Error encountered resolving symbol values statically. Calling function 'OpaqueToken', function calls
 are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving sy
mbol CLOUDINARY_LIB in C:/itj/itjfrontend/node_modules/@cloudinary/angular/src/cloudinary.module.d.ts, resolving sym
bol CloudinaryModule.forRoot in C:/itj/itjfrontend/node_modules/@cloudinary/angular/src/cloudinary.module.d.ts, reso
lving symbol AppModule in C:/itj/itjfrontend/src/app/app.module.ts, resolving symbol AppModule in C:/itj/itjfrontend
/src/app/app.module.ts
    at Error (native)
    at syntaxError (C:\itj\itjfrontend\node_modules\@angular\compiler\bundles\compiler.umd.js:1725:34)
    at simplifyInContext (C:\itj\itjfrontend\node_modules\@angular\compiler\bundles\compiler.umd.js:24949:23)
    at StaticReflector.simplify (C:\itj\itjfrontend\node_modules\@angular\compiler\bundles\compiler.umd.js:24961:13)
    at StaticReflector.annotations (C:\itj\itjfrontend\node_modules\@angular\compiler\bundles\compiler.umd.js:24391:
41)
    at _getNgModuleMetadata (C:\itj\itjfrontend\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (C:\itj\itjfrontend\node_modules\@angular\compiler-cli\src\ngtools_impl.js
:109:26)
    at Object.listLazyRoutesOfModule (C:\itj\itjfrontend\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:2
2)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\itj\itjfrontend\node_modules\@angular\compiler-cli\src\n
gtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (C:\itj\itjfrontend\node_modules\@ngtools\webpack\src\plugin.js:212:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (C:\itj\itjfrontend\node_modules\@ngtools\webpack\src\p
lugin.js:448:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)

Any solution?

**Comment by eitanp461** [comment]
@urstack please provide more information.
- Which Angular version are you using?
- Which version of the SDK are you using?
- Can you share your module setup code? (*.module.ts)
- Have you reviewed the samples in this repository?

Thanks,
Eitan

**Comment by eitanp461** [comment]
@urstack closing due to time elapsed. Please re-open if you are still experiencing the problem.
