### ISSUE TITLE
Add support for universal server side rendering

### ISSUE THREAD

**Issue by dottodot** [cloudinary/cloudinary_angular#93]
When rendering pages server side is doesn't work. At least one issue is because of the use of `MutationObserver` which is browser only.

Here's the errors is causes.

```
ERROR ReferenceError: MutationObserver is not defined
    at CloudinaryImage.ngOnInit (/node_modules/@cloudinary/angular-4.x/src/cloudinary-image.component.js:23:29)
    at checkAndUpdateDirectiveInline (/node_modules/@angular/core/bundles/core.umd.js:10868:19)
    at checkAndUpdateNodeInline (/node_modules/@angular/core/bundles/core.umd.js:12364:17)
    at checkAndUpdateNode (/node_modules/@angular/core/bundles/core.umd.js:12303:16)
    at prodCheckAndUpdateNode (/node_modules/@angular/core/bundles/core.umd.js:12997:5)
    at Object.updateDirectives (/dist-server/main.bundle.js:1:155164)
    at Object.updateDirectives (/node_modules/@angular/core/bundles/core.umd.js:12754:72)
    at checkAndUpdateView (/node_modules/@angular/core/bundles/core.umd.js:12270:14)
    at callViewAction (/node_modules/@angular/core/bundles/core.umd.js:12635:21)
    at execComponentViewsAction (/node_modules/@angular/core/bundles/core.umd.js:12567:13)
    at checkAndUpdateView (/node_modules/@angular/core/bundles/core.umd.js:12276:5)
    at callViewAction (/node_modules/@angular/core/bundles/core.umd.js:12635:21)
    at execComponentViewsAction (/node_modules/@angular/core/bundles/core.umd.js:12567:13)
    at checkAndUpdateView (/node_modules/@angular/core/bundles/core.umd.js:12276:5)
    at callViewAction (/node_modules/@angular/core/bundles/core.umd.js:12635:21)
    at execEmbeddedViewsAction (/node_modules/@angular/core/bundles/core.umd.js:12593:17)
```

```
TypeError: Cannot read property 'disconnect' of undefined
    at CloudinaryImage.ngOnDestroy (/node_modules/@cloudinary/angular-4.x/src/cloudinary-image.component.js:32:22)
    at callProviderLifecycles (/node_modules/@angular/core/bundles/core.umd.js:11220:18)
    at callElementProvidersLifecycles (/node_modules/@angular/core/bundles/core.umd.js:11189:13)
    at callLifecycleHooksChildrenFirst (/node_modules/@angular/core/bundles/core.umd.js:11173:17)
    at destroyView (/node_modules/@angular/core/bundles/core.umd.js:12509:5)
    at callViewAction (/node_modules/@angular/core/bundles/core.umd.js:12655:13)
    at execComponentViewsAction (/node_modules/@angular/core/bundles/core.umd.js:12567:13)
    at destroyView (/node_modules/@angular/core/bundles/core.umd.js:12508:5)
    at callViewAction (/node_modules/@angular/core/bundles/core.umd.js:12655:13)
    at execEmbeddedViewsAction (/node_modules/@angular/core/bundles/core.umd.js:12593:17)
```

**Comment by dottodot** [comment]
OK looks like `MutationObserver` is the least of the issues when it comes to getting it working with Universal.

Can anyone confirm if this is ever likely to be supported and if so how soon as I'm getting close to the end of a project that needs it, and need to know if I need to look at an alternative solution.

**Comment by roeeba** [comment]
Hi, @dottodot. Thank you for reporting this. Our dev team will review this, we will update as soon as we have any insights.

**Comment by dottodot** [comment]
Ok no worries I've gone with using my own custom module for now, tried to modify this but there's too much reliance on client only code.

**Comment by Tomdrouv1** [comment]
Hi! Any news for that issue ?

**Comment by eitanp461** [comment]
@Tomdrouv1 https://github.com/cloudinary/cloudinary_angular/pull/120 fixes this issue. I will try to publish a new version in a few days

**Comment by mlb6** [comment]
@eitanp461 I'm waiting for this fix. Do you have an ETA for the new version of the library? Is there a way to use your PR with npm ? 
I've tried to change the package.json dependency to use your PR, but it does not seem to work.
`        
"@cloudinary/angular-5.x": "cloudinary/cloudinary_angular#universal-rendering",
`

**Comment by eitanp461** [comment]
@mlb6 @Tomdrouv1 @dottodot our [latest release](https://github.com/cloudinary/cloudinary_angular/releases/tag/(5.x)1.0.1) should resolve this issue.

You can install it with `npm install @cloudinary/angular-5.x@^1.0.1`.
